#########################
# project configuration #
#########################

language: cpp

###################
# global settings #
###################

dist: trusty

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
  - secure: "j3gxQHpmALWW1VYvX2+rv/xJ2H32W0SQXkyY83PY/PJxphuiIxWtSAM6wn0SWgBBKIi/1IAUU7xiEQewodkMXB0hjLxUDEsr7nhONPxkdFmgM4nOuqDmR2XJPACpWZV8H1aDxl37vYeWCIio0o2Q1TxtCFz4cENpVmbfuGnq3RCdDWkiwvzQqnXmk0Ac8hRS6KrWwBGOeoCFiR7+/wf0/6lYZZB+KBY7Vjuc40Zv3KZIH4tDfokrQDBmXluV4pQiPc1yz7xy180HNs2pRSTlEfknKGm/Go/wnEVu+OiEugVNt/mP1PRFV52+QuKnjqjOkrtlnEM5al/tza/PAyNdGOEoowAyjMJ8gOIw0NUWXIFZ8EQ0cvgVpLq2Azaamiq43wCVRrH7Ybg7lAVZt8+aQz7CsSbq08qS+OjxRijKxZ4pSRcYoeyXWmZ9K2rRyrJUQTE/v5i0EEgOdFwInxeOxlAgrHu1FhF9gAY+Bgb+O7XPFZTnkHkJlVghk+/mTHLVJpJ03t9gdYrqrENH7m2VfeE+q5zjxRuejLzWzrH5fSJewc3E4IUQqiJfM3NcS7Ra+p5ToRyhm/bnYJotptW6PAV2rJUK3PvLL+uLkSooHDoT/wRi9PvgKzSuXcs0pW7w0Uep0VlpJBzuMi3plI9pY/QDjnIlWwCzRCByWQ3wFsY="

################
# build matrix #
################

matrix:
  include:
  - env: CXX_COMPILER=g++-4.9
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.9
        - valgrind

  - env: CXX_COMPILER=g++-5
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - valgrind

  - env: CXX_COMPILER=g++-6
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
        - valgrind

  - env: CXX_COMPILER=clang++-3.7
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
        packages:
        - clang-3.7
        - valgrind

  - env: CXX_COMPILER=clang++-3.8
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.8
        packages:
        - clang-3.8
        - valgrind

  - env: CXX_COMPILER=clang++-3.9
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.9
        packages:
        - clang-3.9
        - valgrind

  - env:
    - SPECIAL=clang-static
    - ASAN="ON"
    - MSAN="ON"
    - TSAN="ON"
    - UBSAN="ON"
    - STATIC_ANALYZER="ON"
    - CLANG_FORMAT="ON"
    - CLANG_TIDY="ON"
    - PREFIX_TOOL="scan-build"
    compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - clang
    install:
    - scan-build cmake .. -DCMAKE_CXX_FLAGS='-Wall -Wextra'
    - scan-build make
    script: ''

  - env: SPECIAL=coverity
    addons:
      coverity_scan:
        project:
          name: "cb-geo/lbmdem"
          description: "LBM-DEM Coverity scan build submitted via Travis CI"
        notification_email: cued.geomechanics@gmail.com
        build_command_prepend: "cmake ."
        build_command:   "make"
        branch_pattern: coverity_scan
    script: ''


################
# build script #
################
before_install:
    - git clone https://github.com/kokkos/kokkos.git && cd kokkos && mkdir -p $HOME/kokkos && mkdir build && cd build && ../generate_makefile.bash --with-openmp --prefix=$HOME/kokkos && make && make install && cd ../.. && pwd
    - mkdir build
    - cd build

install:
    - cmake .. -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DCMAKE_CXX_FLAGS='-Wall -Wextra -Werror -Wno-unused-parameter -Wno-missing-braces' -DKOKKOS_ROOT=$HOME/kokkos
    - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make ; fi

script:
    - ctest -VV
    - ctest -VV -D ExperimentalMemCheck

notifications:
  slack:
    rooms:
      - cb-geo:0N3fJy823MGsJvcDB91m4p8H#lbmdem

